# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 12:20
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import elbow.apps.document.models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, db_index=True, editable=False, max_length=22)),
                ('name', models.CharField(max_length=128)),
                ('document', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=elbow.apps.document.models._document_upload_path)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
