# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('system', 'System Documents'), ('order', 'Order Document')], db_index=True, default='system', max_length=64),
        ),
    ]
