# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20160205_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('project', 'Project Document'), ('order', 'Order Document'), ('loan_agreement', 'Large Sum Agreement')], db_index=True, default='project', max_length=64),
        ),
    ]
