# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='login_required',
            field=models.BooleanField(default=False),
        ),
    ]
