# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_document_login_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('document.document',),
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('document.document',),
        ),
    ]
