# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-18 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_add_existing_user_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='send_news_and_info',
            field=models.NullBooleanField(db_index=True),
        ),
    ]
