# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-18 13:31
from __future__ import unicode_literals

from django.db import migrations, models


def set_send_news_and_info_from_data_value(apps, schema_editor):
    UserProfile = apps.get_model("public", "UserProfile")
    for up in UserProfile.objects.all():
        if up.data.get('send_news_and_info', False) in ['on', True, 1, '1', 'yes']:
            up.send_news_and_info = True
        else:
            up.send_news_and_info = False
        up.save(update_fields=['send_news_and_info'])



class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_userprofile_send_news_and_info'),
    ]

    operations = [
        migrations.RunPython(set_send_news_and_info_from_data_value),
    ]
