# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 08:01
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import elbow.apps.project.models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('proposition', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_description', models.CharField(blank=True, max_length=255, null=True)),
                ('use_payment_options', models.CharField(choices=[(b'pending', b'Pending')], db_index=True, default=b'no', max_length=3)),
                ('image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=elbow.apps.project.models._image_upload_path)),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('status', models.CharField(choices=[(b'pending', b'Pending')], db_index=True, default=b'pending', max_length=64)),
                ('expiration', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents', models.ManyToManyField(to='document.Document')),
            ],
        ),
    ]
