# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 08:29
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20160217_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
    ]
