# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 09:01
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20160218_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='interest_length',
            new_name='interest_term',
        ),
        migrations.AlterField(
            model_name='project',
            name='lat_long',
            field=geoposition.fields.GeopositionField(default=(51.1655111, 6.2737308), max_length=42),
        ),
    ]
