# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20160218_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='project',
            name='interest_term',
            field=models.CharField(blank=True, help_text='Format: 12m, 36m, 3y, 7y', max_length=24, null=True),
        ),
    ]
