# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 08:03
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import elbow.apps.project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20160527_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='loan_agreement_doc',
            field=models.FileField(max_length=255, blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=elbow.apps.project.models._doc_upload_path, verbose_name='Loan Agreement'),
        ),
        migrations.AlterField(
            model_name='project',
            name='term_sheet_doc',
            field=models.FileField(max_length=255, blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=elbow.apps.project.models._doc_upload_path, verbose_name='Term Sheet'),
        ),
    ]
