# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-24 10:12
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import elbow.apps.project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20160609_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='term_sheet_doc',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=elbow.apps.project.models._doc_upload_path, verbose_name='Term Sheet'),
        ),
    ]
