# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-06 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20160824_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
