# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-22 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_project_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_available',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='If present the detail page will redirect here', null=True, verbose_name='Redirect URL'),
        ),
    ]
