# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20160122_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(b'pending', b'Pending'), (b'new', b'New'), (b'paid', b'Paid'), (b'canceled', b'Canceled')], db_index=True, default=b'pending', max_length=64),
        ),
    ]
