# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20160122_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[(b'bank_transfer', 'Bank transfer'), (b'prepay', 'Manual bank transfer')], db_index=True, default=b'bank_transfer', max_length=24),
        ),
    ]
