# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('order', '0006_auto_20160203_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='documents',
            field=models.ManyToManyField(to='document.Document'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[(b'manual_bank_tx', 'Manual bank transfer'), (b'debit', 'Bank debit')], db_index=True, default=b'debit', max_length=24),
        ),
    ]
