# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20160210_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[(b'debit', 'Bank debit'), (b'prepay', 'Manual bank transfer')], db_index=True, default=b'debit', max_length=24),
        ),
    ]
