# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20160211_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(b'created', 'Order Created (1/3)'), (b'loan_agreement', 'Loan Agreement (2/3)'), (b'processing', 'Processing Payment  (3/3)'), (b'paid', 'Paid'), (b'paid_manually', 'Manually Paid'), (b'failed', 'Payment Failed'), (b'cancelled', 'Payment Cancelled')], db_index=True, default=b'created', max_length=64),
        ),
    ]
