# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20160224_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
