# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20160225_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_number',
        ),
    ]
